 language: python

 dist: bionic

 python:
     - "3.7"
 env:
   global:
     - PLATFORMIO_SETTING_ENABLE_TELEMETRY: "no"
     - PLATFORMIO_SETTING_STRICT_SSL: "yes"

 cache:
     directories:
         - "~/.platformio"

 install:
     - pip install -U platformio
     - platformio update

 script:
     - platformio run

