 language: python

 dist: bionic

 python:
     - "3.7"

 cache:
     directories:
         - "~/.platformio"

 install:
     - pip install -U platformio
     - ./setup-pio-settings.sh
     - platformio update

 script:
     - platformio run

