language: minimal

dist: bionic

services:
  - docker

env:
  global:
    - DOCKER_IMG="registry.gitlab.com/offa/docker-images"

jobs:
  include:
    - language: python
      python: 3.8
      env:
        - COMPILER: pio
        - PLATFORMIO_SETTING_ENABLE_TELEMETRY: "no"
        - PLATFORMIO_SETTING_STRICT_SSL: "yes"
      cache:
        directories:
          - "~/.platformio"

    - language: minimal
      env:
        - COMPILER: gcc-10

    - language: minimal
      env:
        - COMPILER: gcc-7

    - language: minimal
      env:
        - COMPILER: clang-10


install:
  - |
    if [ "${COMPILER}" == "pio" ]; then
      pip install -U platformio
      platformio update
    else
      docker pull ${DOCKER_IMG}/${COMPILER}:stable
    fi

script:
  - |
    if [ "${COMPILER}" == "pio" ]; then
      platformio run
    else
      docker run --cap-add SYS_PTRACE -v ${PWD}:/mnt -it ${DOCKER_IMG}/${COMPILER} /bin/bash -c "cd /mnt; script/ci_build.sh"
    fi
