name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc-12
          - gcc-11
          - gcc-10
          - clang-16
          - clang-15
          - clang-14
          - clang-13
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}:stable"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: script/ci_build.sh

  build_platformio:
    runs-on: ubuntu-latest
    name: "PlatformIO"
    steps:
      - uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Setup
        run: |
          pip install -U -r requirements.txt
          ./setup-pio-settings.sh
          pio pkg update
      - name: Build
        run: pio run

  formatting-check:
    name: "formatting"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: DoozyX/clang-format-lint-action@master
      name: "Verify formatting"
      with:
        clangFormatVersion: 14

