name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc-11
          - gcc-10
          - gcc-7
          - clang-13
          - clang-12
          - clang-11
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}:stable"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: script/ci_build.sh

  build_platformio:
    runs-on: ubuntu-latest
    name: "PlatformIO"
    steps:
      - uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Setup
        run: |
          pip install -U -r requirements.txt
          ./setup-pio-settings.sh
          pio update
      - name: Build
        run: pio run
