name: ci

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc:15
          - gcc:14
          - clang:20
          - clang:19
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: script/ci_build.sh

  build_platformio:
    runs-on: ubuntu-latest
    name: "PlatformIO"
    steps:
      - uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Setup
        run: |
          pip install -U -r requirements.txt
          ./setup-pio-settings.sh
          pio pkg update
      - name: Build
        run: pio run

  formatting-check:
    name: "formatting"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: jidicula/clang-format-action@main
      name: "Verify formatting"
      with:
        clang-format-version: 19

